### ISSUE TITLE
Multiple Presses on Start Game

### ISSUE THREAD

**Issue by DylanMcBean** [mark-boots/canvasShooter#1]
if the user presses the **Start Game** button multiple times; When the game starts the *enemies/circles* have an increasing velocity that makes the game a lot harder

**Comment by mark-boots** [comment]
> if the user presses the **Start Game** button multiple times; When the game starts the _enemies/circles_ have an increasing velocity that makes the game a lot harder

Thanks for the feedback. I fixed it by hiding the startbutton directly after a click
